# Databricks notebook source
# MAGIC %md
# MAGIC ### Example Exploratory Notebook
# MAGIC
# MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
# MAGIC
# MAGIC **Note**: This notebook is not executed as part of the pipeline.

# COMMAND ----------

from pyspark.sql.functions import col

image_meta = {"spark.contentAnnotation": '{"mimeType": "image/jpeg"}'}

display(
    spark.table("cuisine_vision_catalog.silver.cuisine_american")
    .withColumn("processed_image_data", 
               col("processed_image_data").alias("processed_image_data", metadata=image_meta))
    .select("image_id", "food_type", "processed_image_data")
    .limit(3)
)
